spring:
  datasource:
    url: jdbc:h2:mem:chuh;DATABASE_TO_UPPER=false
    username: bob
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      path: /ciul
